name: Integration

on: push

jobs:
  test:
    name: TEST
    uses: ./.github/workflows/pipeline.yml
  finish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "CONFIRMING OUTPUT: ${{ needs.test.outputs.tag }}"