name: Pipeline

on:
  workflow_call:
    outputs:
      tag:
        description: "SAMPLE TAG"
        value: ${{ jobs.main.outputs.tag }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set.outputs.tag }}
    steps:
      - id: set
        run: echo "tag=HELLO WORLD MARTIN" >> "$GITHUB_OUTPUT"

