name: Pipeline

on:
  workflow_call:
    outputs:
      tag:
        description: "SAMPLE TAG"
        value: ${{ jobs.main.outputs.tag }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      tag: "HELLO WORLD MARTIN"
